CREATE TABLE llm_audit (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rcpt_no         VARCHAR(14)  NOT NULL,
    model           VARCHAR(100) NOT NULL,
    prompt_hash     VARCHAR(64)  NOT NULL,
    input_tokens    INTEGER,
    output_tokens   INTEGER,
    latency_ms      INTEGER       NOT NULL CHECK (latency_ms >= 0),
    cost_usd        NUMERIC(10,8) CHECK (cost_usd IS NULL OR cost_usd >= 0),
    success         BOOLEAN       NOT NULL,
    error_message   TEXT,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_llm_audit_rcpt_no    ON llm_audit (rcpt_no);
CREATE INDEX idx_llm_audit_created_at ON llm_audit (created_at DESC);
CREATE INDEX idx_llm_audit_model_ok   ON llm_audit (model, success);

COMMENT ON TABLE llm_audit IS 'Append-only audit row for every LLM call (success or failure)';
COMMENT ON COLUMN llm_audit.prompt_hash IS 'SHA-256 hex of the variable portion of the prompt';
COMMENT ON COLUMN llm_audit.cost_usd IS 'Null when the call failed before producing tokens';
