CREATE TABLE payment_log (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rcpt_no_accessed   VARCHAR(14),
    endpoint           VARCHAR(200) NOT NULL,
    amount_usdc        NUMERIC(12,6) NOT NULL CHECK (amount_usdc >= 0),
    payer_address      VARCHAR(42)  NOT NULL,
    network            VARCHAR(40)  NOT NULL,
    facilitator_tx_id  VARCHAR(80),
    signature_hash     VARCHAR(64)  NOT NULL,
    settled_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_payment_log_settled_at  ON payment_log (settled_at DESC);
CREATE INDEX idx_payment_log_endpoint    ON payment_log (endpoint);
CREATE INDEX idx_payment_log_payer       ON payment_log (payer_address);
CREATE UNIQUE INDEX uq_payment_log_sig   ON payment_log (signature_hash);

COMMENT ON TABLE payment_log IS 'One row per settled x402 payment, for revenue reporting and tax prep';
COMMENT ON COLUMN payment_log.amount_usdc IS 'Amount in USDC as decimal (6 decimals to match USDC atomic precision)';
COMMENT ON COLUMN payment_log.network IS 'eip155:8453 = Base mainnet, eip155:84532 = Base Sepolia';
COMMENT ON COLUMN payment_log.signature_hash IS 'SHA-256 hex of the X-PAYMENT header that funded this row';
